# Cosas a limpiar en df_bank

- **Unnamed** --> No aporta información. Se podría eliminar. **HECHO**
- **age** --> cambiar a tipo entero (int64) porque la edad no se mide con decimales **HECHO**
- **job** --> sustituir "-" de "blue-collar" y "self-employed" por "_". **HECHO**
- **marital** --> cambiar a minúscula la columna **HECHO**   
- **education** --> cambiar "." por "_" **HECHO** 
- **default** --> Cambiar a dtype boolean (valores booleanos) y añadir columna nueva str si y no. **HECHO**
- **housing** --> Cambiar a dtype boolean (valores booleanos) y añadir columna nueva str si y no. **HECHO**
- **loan** --> Cambiar a dtype boolean (valores booleanos) y añadir columna nueva str si y no. **HECHO**
- **contact** --> OK
- **duration** --> OK
- **campaing** --> OK
- **pdays** --> OK. ¿Qué significa 999?. Crear una nueva columna y sustituir 999 por "nulo" y mantener en formato "int64" **HECHO**
- **previous** --> OK
- **poutcome** --> Cambiar a minuscula **HECHO**
- **emp.var.rate** --> Sustituir en el nombre de la columna, "." por "_" del nombre de la columna.  **HECHO** 
- **cons.price.idx** --> Sustituir en el nombre de la columna, "." por "_" del nombre de la columna.  **HECHO** . Cambiar el "," de los decimales a "." para ser tipo float64 **HECHO**
- **cons.conf.idx** --> Sustituir en el nombre de la columna, "." por "_" del nombre de la columna.  **HECHO** . Cambiar el "," de los decimales a "." para ser tipo float64 **HECHO**
- **euribor3m** --> Cambiar el "," de los decimales a "." para ser tipo float64 **HECHO**
- **nr.employed** --> Sustituir em el nombre de la columna, "." por "_" del nombre de la columna.  **HECHO** . Cambiar el "," de los decimales a "." para ser tipo float64 **HECHO**
- **y** --> Cambiar a dtype boolean (valores booleanos) y añadir columna nueva str si y no.
- **latitude** --> OK
- **longitude** --> OK
- **date** --> cambiar a tipo fecha **HECHO**
- **contact_month** --> Nueva columna extraída de date
- **contact_year** --> Nueva columna extraída de date
- **id_** --> Eliminar "_". **HECHO**

In [1]:
# Tratamiento de datos

import pandas as pd
pd.set_option('display.max_columns', None)

import numpy as np

# ----------

# Exploración de archivos
import sys
sys.path.append('../../../')

#----------

# Funciones personalizadas
from src import sp_cleaning as sc

Cargamos los datos y hacemos una copia

In [2]:
df_bank = pd.read_csv('../../../data/bank-additional.csv')
df_clean = df_bank.copy()

Elimino la columna "Unnamed" porque no aporta información ni valor al dataframe

In [ ]:
sc.drop_columns(df_clean, ["Unnamed: 0"])

In [3]:
df_clean.sample(5)

,Unnamed: 0,age,job,marital,education,default,housing,loan,contact,duration,campaign,pdays,previous,poutcome,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,y,date,latitude,longitude,id_
31706,31850,NaN,blue-collar,SINGLE,basic.4y,0.0,1.0,0.0,cellular,560,3,999,0,NONEXISTENT,-1.8,"92,893","-46,2","1,327","5099,1",no,2-julio-2015,24.608,-105.755,a7ceb1e2-f0b4-406a-a542-0af20e08e046
26568,26690,34.0,unemployed,MARRIED,university.degree,0.0,1.0,0.0,cellular,266,3,999,0,NONEXISTENT,-0.1,"93,2",-42,NaN,"5195,8",no,3-febrero-2015,36.915,-77.378,00edd21e-165e-453a-8033-f8b9d40c4369
40887,41054,31.0,student,SINGLE,university.degree,0.0,0.0,0.0,cellular,508,1,999,0,NONEXISTENT,-1.1,"94,601","-49,5",NaN,"4963,6",yes,6-julio-2019,34.024,-120.744,369ed8f1-0fd1-40b2-bf22-9401dabbba6b
17504,17601,58.0,unemployed,DIVORCED,high.school,0.0,0.0,0.0,cellular,377,4,999,0,NONEXISTENT,1.4,"93,918","-42,7","4,962","5228,1",no,6-septiembre-2018,32.684,-76.319,716c52dc-4ff3-434c-8d30-0c92ee08936e
36904,37071,26.0,admin.,SINGLE,university.degree,0.0,1.0,0.0,cellular,153,1,999,0,NONEXISTENT,-2.9,"92,469","-33,6",NaN,"5076,2",yes,29-octubre-2016,32.044,-101.604,85730932-ea84-4a15-bc35-152a45f6a990

Cambio el formato de la columna "edad" a "int64" porque la edad se mide en número enteros, no en decimales.

In [4]:
df_clean['age'] = df_clean['age'].astype("Int64")

In [5]:
df_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 43000 entries, 0 to 42999
Data columns (total 24 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Unnamed: 0      43000 non-null  int64
 1   age             37880 non-null  Int64
 2   job             42655 non-null  object
 3   marital         42915 non-null  object
 4   education       41193 non-null  object
 5   default         34019 non-null  float64
 6   housing         41974 non-null  float64
 7   loan            41974 non-null  float64
 8   contact         43000 non-null  object
 9   duration        43000 non-null  int64
 10  campaign        43000 non-null  int64
 11  pdays           43000 non-null  int64
 12  previous        43000 non-null  int64
 13  poutcome        43000 non-null  object
 14  emp.var.rate    43000 non-null  float64
 15  cons.price.idx  42529 non-null  object
 16  cons.conf.idx   43000 non-null  object
 17  euribor3m       33744 non-null  object
 18  nr.employed     43000 non-null  object
 19  y               43000 non-null  object
 20  date            42752 non-null  object
 21  latitude        43000 non-null  float64
 22  longitude       43000 non-null  float64
 23  id_             43000 non-null  object
dtypes: Int64(1), float64(6), int64(5), object(12)
memory usage: 7.9+ MB

Cambio a minúscula todas las columnas categóricas del dataframe

In [6]:
sc.minus(df_clean)

In [7]:
df_clean.sample(5)

,Unnamed: 0,age,job,marital,education,default,housing,loan,contact,duration,campaign,pdays,previous,poutcome,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,y,date,latitude,longitude,id_
13723,13820,31,technician,married,professional.course,0.0,0.0,0.0,cellular,3643,1,999,0,nonexistent,1.4,"93,918","-42,7","4,963","5228,1",yes,21-febrero-2016,27.662,-85.169,b703d2c2-d027-4813-ac0b-890cbab4534b
25561,25683,36,management,married,university.degree,0.0,0.0,0.0,cellular,498,1,999,0,nonexistent,-0.1,"93,2",-42,"4,12","5195,8",no,20-noviembre-2019,36.122,-114.189,2076ccbd-4eee-487e-bb15-b6c69b2fad18
22545,22642,44,blue-collar,married,illiterate,0.0,0.0,0.0,cellular,460,1,999,0,nonexistent,1.4,"93,444","-36,1","4,964","5228,1",no,28-junio-2017,35.190,-113.975,8af632f4-018c-4ff1-9a3d-349eb232e2b2
1119,1216,<NA>,retired,married,NaN,0.0,1.0,0.0,telephone,96,2,999,0,nonexistent,1.1,"93,994","-36,4","4,855",5191,no,20-febrero-2018,48.266,-121.235,a6c7df44-f88f-422a-bf35-2aa2c69592ff
10829,10926,26,blue-collar,married,basic.4y,0.0,0.0,0.0,telephone,94,1,999,0,nonexistent,1.4,"94,465","-41,8","4,962","5228,1",no,29-abril-2015,38.453,-121.850,3c29eae3-ff38-407d-8484-0696d5fd3059

Normalizamos el texto de las columnas del dataset para una mejor comprensión

In [8]:
sc.normalizar_texto(df_clean)

Cambiamos el nombre de algunas columnas más específicas que no están dentro de la función "normalizar_texto"

In [9]:
df_clean.columns = df_clean.columns.str.replace('.', '_').str.lower()
df_clean = df_clean.rename(columns={'id_': 'id'})
df_clean = df_clean.rename(columns={'euribor3m': 'euribor_3m'})

Cambiamos el formato de la columna "date" para que lo reconozca cuando lo cambie a tipo "datetime"

In [11]:
df_clean['date'] = df_clean['date'].str.replace('_', '-')

Cambio la columna "date" a tipo "datetime" con una función.

In [12]:
sc.convierte_datetime(df_clean, 'date')

Convertimos a booleanos la columna "housing"

In [13]:
sc.boolean(df_clean,'housing')

Como ha funcionado la función "boolean", lo repetimos para las columnas "default" y "loan", pero en el archivo final.

Creamos nuevas columnas "str" con los valores booleanos

In [14]:
sc.boolean_to_str(df_clean, 'housing', 'housing_str')

,unnamed: 0,age,job,marital,education,default,housing,loan,contact,duration,campaign,pdays,previous,poutcome,emp_var_rate,cons_price_idx,cons_conf_idx,euribor_3m,nr_employed,y,date,latitude,longitude,id,housing_str
0,0,<NA>,housemaid,married,basic_4y,0.0,False,0.0,telephone,261,1,999,0,nonexistent,1.1,"93,994","_36,4","4,857",5191,no,2019-08-02,41.495,-71.233,089b39d8_e4d0_461b_87d4_814d71e0e079,no
1,1,57,services,married,high_school,NaN,False,0.0,telephone,149,1,999,0,nonexistent,1.1,"93,994","_36,4",NaN,5191,no,2016-09-14,34.601,-83.923,e9d37224_cb6f_4942_98d7_46672963d097,no
2,2,37,services,married,high_school,0.0,True,0.0,telephone,226,1,999,0,nonexistent,1.1,"93,994","_36,4","4,857",5191,no,2019-02-15,34.939,-94.847,3f9f49b5_e410_4948_bf6e_f9244f04918b,yes
3,3,40,admin_,married,basic_6y,0.0,False,0.0,telephone,151,1,999,0,nonexistent,1.1,"93,994","_36,4",NaN,5191,no,2015-11-29,49.041,-70.308,9991fafb_4447_451a_8be2_b0df6098d13e,no
4,4,56,services,married,high_school,0.0,False,1.0,telephone,307,1,999,0,nonexistent,1.1,"93,994","_36,4",NaN,5191,no,2017-01-29,38.033,-104.463,eca60b76_70b6_4077_80ba_bc52e8ebb0eb,no
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
42995,19154,<NA>,admin_,married,university_degree,0.0,False,0.0,cellular,618,2,999,0,nonexistent,1.4,"93,444","_36,1",NaN,"5228,1",yes,2015-10-13,38.147,-105.582,4eed05de_2a98_4227_b488_32122009b638,no
42996,26206,34,technician,married,professional_course,0.0,True,1.0,cellular,42,7,999,0,nonexistent,-0.1,"93,2",_42,NaN,"5195,8",no,2018-03-17,49.235,-112.201,0f0aca88_4088_4fe2_905f_44fb675d9493,yes
42997,15046,<NA>,blue_collar,single,basic_6y,0.0,True,0.0,cellular,391,2,999,0,nonexistent,1.4,"93,918","_42,7",NaN,"5228,1",no,2016-09-15,40.679,-120.015,cadadd4b_7ee5_4019_b13a_ca01bb67ca5b,yes
42998,15280,<NA>,admin_,married,university_degree,NaN,False,0.0,cellular,674,3,999,0,nonexistent,1.4,"93,918","_42,7","4,958","5228,1",no,2019-09-23,27.772,-117.518,5f432048_d515_4bb5_9c94_62db451f88d4,no
42999,27570,<NA>,unemployed,single,university_degree,0.0,False,1.0,cellular,104,2,999,0,nonexistent,-0.1,"93,2",_42,"4,021","5195,8",no,2019-11-06,41.146,-105.026,993bbbd6_4dbc_4a40_a408_f91f8462bee6,no

Extraemos las fechas

In [15]:
df_clean['contact_month'] = df_clean['date'].dt.month_name().str.lower()
df_clean['contact_year'] = df_clean['date'].dt.year.astype('Int64')

In [16]:
df_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 43000 entries, 0 to 42999
Data columns (total 27 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   unnamed: 0      43000 non-null  int64
 1   age             37880 non-null  Int64
 2   job             42655 non-null  object
 3   marital         42915 non-null  object
 4   education       41193 non-null  object
 5   default         34019 non-null  float64
 6   housing         41974 non-null  boolean
 7   loan            41974 non-null  float64
 8   contact         43000 non-null  object
 9   duration        43000 non-null  int64
 10  campaign        43000 non-null  int64
 11  pdays           43000 non-null  int64
 12  previous        43000 non-null  int64
 13  poutcome        43000 non-null  object
 14  emp_var_rate    43000 non-null  float64
 15  cons_price_idx  42529 non-null  object
 16  cons_conf_idx   43000 non-null  object
 17  euribor_3m      33744 non-null  object
 18  nr_employed     43000 non-null  object
 19  y               43000 non-null  object
 20  date            42752 non-null  datetime64[ns]
 21  latitude        43000 non-null  float64
 22  longitude       43000 non-null  float64
 23  id              43000 non-null  object
 24  housing_str     41974 non-null  object
 25  contact_month   42752 non-null  object
 26  contact_year    42752 non-null  Int64
dtypes: Int64(2), boolean(1), datetime64[ns](1), float64(5), int64(5), object(13)
memory usage: 8.7+ MB

Generamos una nueva columna para "pdays" en la que sustituyamos el valor '999' por valor nulo.

In [17]:
df_clean['pdays_clean'] = df_clean['pdays'].replace(999, np.nan).astype('Int64')
media_pdays = df_clean['pdays_clean'].mean()

In [ ]:
df_bank_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 43000 entries, 0 to 42999
Data columns (total 26 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             37880 non-null  Int64
 1   job             42655 non-null  object
 2   marital         42915 non-null  object
 3   education       41193 non-null  object
 4   default         34019 non-null  boolean
 5   housing         41974 non-null  boolean
 6   loan            41974 non-null  float64
 7   contact         43000 non-null  object
 8   duration        43000 non-null  int64
 9   campaign        43000 non-null  int64
 10  pdays           43000 non-null  int64
 11  previous        43000 non-null  int64
 12  poutcome        43000 non-null  object
 13  emp_var_rate    43000 non-null  float64
 14  cons_price_idx  42529 non-null  float64
 15  cons_conf_idx   43000 non-null  float64
 16  euribor3m       33744 non-null  float64
 17  nr_employed     43000 non-null  float64
 18  y               43000 non-null  object
 19  date            42752 non-null  datetime64[ns]
 20  latitude        43000 non-null  float64
 21  longitude       43000 non-null  float64
 22  id              43000 non-null  object
 23  default_str     34019 non-null  object
 24  housing_str     41974 non-null  object
 25  pdays_clean     1588 non-null   Int64
dtypes: Int64(2), boolean(2), datetime64[ns](1), float64(8), int64(4), object(9)
memory usage: 8.1+ MB