# Cosas a limpiar en df_bank

- **Unnamed** --> No aporta información. Se podría eliminar. **HECHO**
- **age** --> cambiar a tipo entero (int64) porque la edad no se mide con decimales **HECHO**
- **job** --> sustituir "-" de "blue-collar" y "self-employed" por "_". **HECHO**
- **marital** --> cambiar a minúscula la columna **HECHO**   
- **education** --> cambiar "." por "_" **HECHO** 
- **default** --> Cambiar a dtype boolean (valores booleanos) y añadir columna nueva str si y no. **HECHO**
- **housing** --> Cambiar a dtype boolean (valores booleanos) y añadir columna nueva str si y no. **HECHO**
- **loan** --> Cambiar a dtype boolean (valores booleanos) y añadir columna nueva str si y no. **HECHO**
- **contact** --> OK
- **duration** --> OK
- **campaing** --> OK
- **pdays** --> OK. ¿Qué significa 999?. Crear una nueva columna y sustituir 999 por "nulo" y mantener en formato "int64" **HECHO**
- **previous** --> OK
- **poutcome** --> Cambiar a minuscula **HECHO**
- **emp.var.rate** --> Sustituir en el nombre de la columna, "." por "_" del nombre de la columna.  **HECHO** 
- **cons.price.idx** --> Sustituir en el nombre de la columna, "." por "_" del nombre de la columna.  **HECHO** . Cambiar el "," de los decimales a "." para ser tipo float64 **HECHO**
- **cons.conf.idx** --> Sustituir en el nombre de la columna, "." por "_" del nombre de la columna.  **HECHO** . Cambiar el "," de los decimales a "." para ser tipo float64 **HECHO**
- **euribor3m** --> Cambiar el "," de los decimales a "." para ser tipo float64 **HECHO**
- **nr.employed** --> Sustituir em el nombre de la columna, "." por "_" del nombre de la columna.  **HECHO** . Cambiar el "," de los decimales a "." para ser tipo float64 **HECHO**
- **y** --> Cambiar a dtype boolean (valores booleanos) y añadir columna nueva str si y no.
- **latitude** --> OK
- **longitude** --> OK
- **date** --> cambiar a tipo fecha **HECHO**
- **contact_month** --> Nueva columna extraída de date
- **contact_year** --> Nueva columna extraída de date
- **id_** --> Eliminar "_". **HECHO**

In [2]:
# Tratamiento de datos

import pandas as pd
pd.set_option('display.max_columns', None)

import numpy as np

# ----------

# Exploración de archivos
import sys
sys.path.append('../../../')

#----------

# Funciones personalizadas
from src import sp_cleaning as sc

Cargamos los datos y hacemos una copia

In [3]:
df_bank = pd.read_csv('../../../data/bank-additional.csv')
df_clean = df_bank.copy()

Elimino la columna "Unnamed" porque no aporta información ni valor al dataframe

In [4]:
sc.drop_columns(df_clean, ["Unnamed: 0"])

In [5]:
df_clean.sample(5)

,age,job,marital,education,default,housing,loan,contact,duration,campaign,pdays,previous,poutcome,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,y,date,latitude,longitude,id_
2015,NaN,technician,MARRIED,basic.9y,0.0,1.0,0.0,telephone,215,1,999,0,NONEXISTENT,1.1,"93,994","-36,4","4,857",5191,no,1-octubre-2015,37.469,-101.020,08914f32-ad3d-4ec0-9496-0c5a9d483b6b
17361,36.0,blue-collar,MARRIED,basic.9y,0.0,0.0,0.0,cellular,63,1,999,0,NONEXISTENT,1.4,"93,918","-42,7","4,962","5228,1",no,13-septiembre-2017,27.524,-100.808,772e9dfc-19b5-46a8-9b43-40dce4c22157
20778,54.0,services,MARRIED,high.school,0.0,1.0,0.0,cellular,250,1,999,0,NONEXISTENT,1.4,"93,444","-36,1","4,964","5228,1",no,25-septiembre-2015,33.374,-82.542,6353dbf1-2001-4372-9802-762c41214b7a
10607,30.0,entrepreneur,MARRIED,professional.course,0.0,1.0,0.0,telephone,775,3,999,0,NONEXISTENT,1.4,"94,465","-41,8","4,961","5228,1",yes,17-octubre-2017,28.022,-82.372,e29d80a5-f3b6-45bb-82cf-0a457f819488
37336,27.0,technician,SINGLE,university.degree,0.0,0.0,0.0,cellular,103,1,4,1,SUCCESS,-2.9,"92,201","-31,4",NaN,"5076,2",no,1-julio-2015,31.705,-83.781,eb7d13ec-59bd-4030-9eab-2169f1ecefba

Cambio el formato de la columna "edad" a "int64" porque la edad se mide en número enteros, no en decimales.

In [6]:
df_clean['age'] = df_clean['age'].astype("Int64")

In [7]:
df_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 43000 entries, 0 to 42999
Data columns (total 23 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             37880 non-null  Int64
 1   job             42655 non-null  object
 2   marital         42915 non-null  object
 3   education       41193 non-null  object
 4   default         34019 non-null  float64
 5   housing         41974 non-null  float64
 6   loan            41974 non-null  float64
 7   contact         43000 non-null  object
 8   duration        43000 non-null  int64
 9   campaign        43000 non-null  int64
 10  pdays           43000 non-null  int64
 11  previous        43000 non-null  int64
 12  poutcome        43000 non-null  object
 13  emp.var.rate    43000 non-null  float64
 14  cons.price.idx  42529 non-null  object
 15  cons.conf.idx   43000 non-null  object
 16  euribor3m       33744 non-null  object
 17  nr.employed     43000 non-null  object
 18  y               43000 non-null  object
 19  date            42752 non-null  object
 20  latitude        43000 non-null  float64
 21  longitude       43000 non-null  float64
 22  id_             43000 non-null  object
dtypes: Int64(1), float64(6), int64(4), object(12)
memory usage: 7.6+ MB

Cambio a minúscula todas las columnas categóricas del dataframe

In [8]:
sc.minus(df_clean)

In [9]:
df_clean.sample(5)

,age,job,marital,education,default,housing,loan,contact,duration,campaign,pdays,previous,poutcome,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,y,date,latitude,longitude,id_
21846,32,technician,married,university.degree,NaN,0.0,0.0,cellular,212,2,999,0,nonexistent,1.4,"93,444","-36,1","4,964","5228,1",no,11-enero-2019,34.086,-67.201,11b4fd54-682b-4fe5-b22b-d5780669fb98
8641,27,blue-collar,married,basic.9y,NaN,0.0,0.0,telephone,235,1,999,0,nonexistent,1.4,"94,465","-41,8","4,864","5228,1",no,12-julio-2019,47.447,-108.692,e53c02ef-e32b-471a-b27d-39b317cacf19
15053,33,services,divorced,high.school,0.0,0.0,0.0,cellular,654,1,999,0,nonexistent,1.4,"93,918","-42,7","4,958","5228,1",no,8-octubre-2017,24.644,-70.893,a162aa9f-6c54-447d-9a19-b202d25c871a
1785,58,entrepreneur,married,university.degree,NaN,0.0,0.0,telephone,107,4,999,0,nonexistent,1.1,"93,994","-36,4","4,855",5191,no,8-julio-2016,34.605,-102.327,14e7b608-abca-420b-b793-a733ddb29083
25203,<NA>,blue-collar,married,basic.4y,NaN,1.0,0.0,cellular,586,2,999,0,nonexistent,-0.1,"93,2",-42,"4,153","5195,8",no,30-diciembre-2018,39.795,-121.605,43e2132a-59ec-44b2-bbca-1357f208d872

Normalizamos el texto de las columnas del dataset para una mejor comprensión

In [10]:
sc.normalizar_texto(df_clean)

Cambiamos el nombre de algunas columnas más específicas que no están dentro de la función "normalizar_texto"

In [11]:
df_clean.columns = df_clean.columns.str.replace('.', '_').str.lower()
df_clean = df_clean.rename(columns={'id_': 'id'})
df_clean = df_clean.rename(columns={'euribor3m': 'euribor_3m'})

Cambiamos el formato de la columna "date" para que lo reconozca cuando lo cambie a tipo "datetime"

In [12]:
df_clean['date'] = df_clean['date'].str.replace('_', '-')

Cambio la columna "date" a tipo "datetime" con una función.

In [13]:
sc.convierte_datetime(df_clean, 'date')

Convertimos a booleanos la columna "housing"

In [14]:
sc.boolean(df_clean,'housing')

Como ha funcionado la función "boolean", lo repetimos para las columnas "default" y "loan", pero en el archivo final.

Creamos nuevas columnas "str" con los valores booleanos

In [15]:
sc.boolean_to_str(df_clean, 'housing', 'housing_str')

Extraemos las fechas

In [16]:
df_clean['contact_month'] = df_clean['date'].dt.month_name().str.lower()
df_clean['contact_year'] = df_clean['date'].dt.year.astype('Int64')

In [17]:
df_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 43000 entries, 0 to 42999
Data columns (total 26 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             37880 non-null  Int64
 1   job             42655 non-null  object
 2   marital         42915 non-null  object
 3   education       41193 non-null  object
 4   default         34019 non-null  float64
 5   housing         41974 non-null  boolean
 6   loan            41974 non-null  float64
 7   contact         43000 non-null  object
 8   duration        43000 non-null  int64
 9   campaign        43000 non-null  int64
 10  pdays           43000 non-null  int64
 11  previous        43000 non-null  int64
 12  poutcome        43000 non-null  object
 13  emp_var_rate    43000 non-null  float64
 14  cons_price_idx  42529 non-null  object
 15  cons_conf_idx   43000 non-null  object
 16  euribor_3m      33744 non-null  object
 17  nr_employed     43000 non-null  object
 18  y               43000 non-null  object
 19  date            42752 non-null  datetime64[ns]
 20  latitude        43000 non-null  float64
 21  longitude       43000 non-null  float64
 22  id              43000 non-null  object
 23  housing_str     41974 non-null  object
 24  contact_month   42752 non-null  object
 25  contact_year    42752 non-null  Int64
dtypes: Int64(2), boolean(1), datetime64[ns](1), float64(5), int64(4), object(13)
memory usage: 8.4+ MB

Generamos una nueva columna para "pdays" en la que sustituyamos el valor '999' por valor nulo.

In [18]:
df_clean['pdays_clean'] = df_clean['pdays'].replace(999, np.nan).astype('Int64')
media_pdays = df_clean['pdays_clean'].mean()

In [20]:
df_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 43000 entries, 0 to 42999
Data columns (total 27 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             37880 non-null  Int64
 1   job             42655 non-null  object
 2   marital         42915 non-null  object
 3   education       41193 non-null  object
 4   default         34019 non-null  float64
 5   housing         41974 non-null  boolean
 6   loan            41974 non-null  float64
 7   contact         43000 non-null  object
 8   duration        43000 non-null  int64
 9   campaign        43000 non-null  int64
 10  pdays           43000 non-null  int64
 11  previous        43000 non-null  int64
 12  poutcome        43000 non-null  object
 13  emp_var_rate    43000 non-null  float64
 14  cons_price_idx  42529 non-null  object
 15  cons_conf_idx   43000 non-null  object
 16  euribor_3m      33744 non-null  object
 17  nr_employed     43000 non-null  object
 18  y               43000 non-null  object
 19  date            42752 non-null  datetime64[ns]
 20  latitude        43000 non-null  float64
 21  longitude       43000 non-null  float64
 22  id              43000 non-null  object
 23  housing_str     41974 non-null  object
 24  contact_month   42752 non-null  object
 25  contact_year    42752 non-null  Int64
 26  pdays_clean     1588 non-null   Int64
dtypes: Int64(3), boolean(1), datetime64[ns](1), float64(5), int64(4), object(13)
memory usage: 8.7+ MB