In [1]:
# Cargamos librerías para análisis de datos
import pandas as pd
import sys
sys.path.append('../../../')
from src import sp_eda as se
pd.set_option('display.max_columns', None) # Utilizamos este comando para visualizar todas las columnas cuando hacemos un muestreo
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

Como el archivo tiene 3 hojas que representan 3 años distintos, pero tienen la misma estructura, lo que hacemos es unificar en un solo dataframe para facilitar el análisis.

In [13]:
xls = pd.ExcelFile('../../../data/customer-details.xlsx')

df_customer = pd.concat(
    [xls.parse(sheet) for sheet in xls.sheet_names],
    ignore_index=True
)

In [14]:
df_customer.sample(5)

,Unnamed: 0,Income,Kidhome,Teenhome,Dt_Customer,NumWebVisitsMonth,ID
5044,5044,76426,0,2,2012-01-17,18,0aa7d582-8dc6-42ad-97df-5744d333a6fe
22204,2089,74568,2,0,2013-10-01,27,b8ed5ba5-87d1-4fe6-a7c0-44ca1e3cbe29
24419,4304,19622,2,2,2013-05-29,9,99f8694d-dca0-43a3-acb6-c625dd683062
1413,1413,54883,0,1,2012-03-28,2,b0698213-81de-4393-a536-62b955e266a4
34746,5666,94138,1,2,2014-08-18,32,eb8aa9d2-caa0-4590-befc-e011bfa8a862

In [15]:
print(f'Nuestro archivo "customer-details" de datos presenta un total de {df_customer.shape[0]} filas y {df_customer.shape[1]} columnas')

Nuestro archivo "customer-details" de datos presenta un total de 43170 filas y 7 columnas

In [16]:
df_customer.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 43170 entries, 0 to 43169
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Unnamed: 0         43170 non-null  int64
 1   Income             43170 non-null  int64
 2   Kidhome            43170 non-null  int64
 3   Teenhome           43170 non-null  int64
 4   Dt_Customer        43170 non-null  datetime64[ns]
 5   NumWebVisitsMonth  43170 non-null  int64
 6   ID                 43170 non-null  object
dtypes: datetime64[ns](1), int64(5), object(1)
memory usage: 2.3+ MB

Valores nulos

In [17]:
df_customer.isnull().sum()

Unnamed: 0           0
Income               0
Kidhome              0
Teenhome             0
Dt_Customer          0
NumWebVisitsMonth    0
ID                   0
dtype: int64

In [18]:
df_customer.isnull().sum()/df_customer.shape[0]*100

Unnamed: 0           0.0
Income               0.0
Kidhome              0.0
Teenhome             0.0
Dt_Customer          0.0
NumWebVisitsMonth    0.0
ID                   0.0
dtype: float64

Valores duplicados

In [19]:
df_customer.duplicated().sum()

np.int64(0)

Columnas categóricas

In [20]:
df_customer.select_dtypes(include= 'object').columns

Index(['ID'], dtype='object')

In [21]:
for col in df_customer.select_dtypes(include= 'object').columns:

    print(col.upper())

    print(df_customer[col].value_counts())

    print('------')

ID
ID
089b39d8-e4d0-461b-87d4-814d71e0e079    1
e9d37224-cb6f-4942-98d7-46672963d097    1
3f9f49b5-e410-4948-bf6e-f9244f04918b    1
9991fafb-4447-451a-8be2-b0df6098d13e    1
eca60b76-70b6-4077-80ba-bc52e8ebb0eb    1
                                       ..
5f432048-d515-4bb5-9c94-62db451f88d4    1
993bbbd6-4dbc-4a40-a408-f91f8462bee6    1
d6271666-319d-42c8-a741-cb22bf2c2093    1
f67fbfa8-6573-414d-a805-b26a2f1b1ceb    1
9727bc06-c11a-461a-a5bb-3d210467cc2a    1
Name: count, Length: 43170, dtype: int64
------

Estadísticos numéricos

In [22]:
display(df_customer.describe().T)

,count,mean,min,25%,50%,75%,max,std
Unnamed: 0,43170.0,7916.022469,0.0,3597.0,7194.5,11705.75,20114.0,5228.248885
Income,43170.0,93227.389622,5841.0,49608.0,93009.5,136740.5,180802.0,50498.181989
Kidhome,43170.0,1.004749,0.0,0.0,1.0,2.0,2.0,0.815996
Teenhome,43170.0,0.998633,0.0,0.0,1.0,2.0,2.0,0.816008
Dt_Customer,43170,2013-05-11 22:09:47.407922176,2012-01-01 00:00:00,2012-07-16 00:00:00,2013-03-01 00:00:00,2014-03-28 00:00:00,2014-12-31 00:00:00,NaN
NumWebVisitsMonth,43170.0,16.59129,1.0,9.0,17.0,25.0,32.0,9.241769

**Función EDA_preliminar**

Vamos a comprobar que la función "eda_preliminar" que hemos definido anteriormete y está en el archivo soporte funciona correctamente.

In [23]:
se.eda_preliminar(df_customer)

,Unnamed: 0,Income,Kidhome,Teenhome,Dt_Customer,NumWebVisitsMonth,ID
23469,3354,14819,0,2,2013-03-02,18,592920e0-f6d9-4ad3-bfd4-d528676ef90c
31597,2517,55398,0,2,2014-01-19,6,ac30e8e0-8746-4418-b48f-bfd6f5dd1d0e
16089,16089,91770,2,2,2012-04-10,16,c1bd46cc-2c4d-45f9-b7af-104142207ba9
19423,19423,140435,0,2,2012-01-09,24,f03021b2-f267-4736-b032-c2e02e1a6eaa
14702,14702,42072,0,2,2012-08-01,14,04dad937-41f5-4074-a810-64625c1bb3d7

---------------
DIMENSIONES
Nuestro conjunto de datos presenta un total de 43170 filas y 7 columnas
---------------
INFO
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 43170 entries, 0 to 43169
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Unnamed: 0         43170 non-null  int64
 1   Income             43170 non-null  int64
 2   Kidhome            43170 non-null  int64
 3   Teenhome           43170 non-null  int64
 4   Dt_Customer        43170 non-null  datetime64[ns]
 5   NumWebVisitsMonth  43170 non-null  int64
 6   ID                 43170 non-null  object
dtypes: datetime64[ns](1), int64(5), object(1)
memory usage: 2.3+ MB

None

---------------
NULOS

Unnamed: 0           0.0
Income               0.0
Kidhome              0.0
Teenhome             0.0
Dt_Customer          0.0
NumWebVisitsMonth    0.0
ID                   0.0
dtype: float64

---------------
DUPLICADOS
Tenemos un total de 0 duplicados
---------------
FRECUENCIAS CATEGÓRICAS
ID
ID
089b39d8-e4d0-461b-87d4-814d71e0e079    1
e9d37224-cb6f-4942-98d7-46672963d097    1
3f9f49b5-e410-4948-bf6e-f9244f04918b    1
9991fafb-4447-451a-8be2-b0df6098d13e    1
eca60b76-70b6-4077-80ba-bc52e8ebb0eb    1
                                       ..
5f432048-d515-4bb5-9c94-62db451f88d4    1
993bbbd6-4dbc-4a40-a408-f91f8462bee6    1
d6271666-319d-42c8-a741-cb22bf2c2093    1
f67fbfa8-6573-414d-a805-b26a2f1b1ceb    1
9727bc06-c11a-461a-a5bb-3d210467cc2a    1
Name: count, Length: 43170, dtype: int64
----------
---------------
ESTADISTICOS NUMÉRICOS

,count,mean,min,25%,50%,75%,max,std
Unnamed: 0,43170.0,7916.022469,0.0,3597.0,7194.5,11705.75,20114.0,5228.248885
Income,43170.0,93227.389622,5841.0,49608.0,93009.5,136740.5,180802.0,50498.181989
Kidhome,43170.0,1.004749,0.0,0.0,1.0,2.0,2.0,0.815996
Teenhome,43170.0,0.998633,0.0,0.0,1.0,2.0,2.0,0.816008
Dt_Customer,43170,2013-05-11 22:09:47.407922176,2012-01-01 00:00:00,2012-07-16 00:00:00,2013-03-01 00:00:00,2014-03-28 00:00:00,2014-12-31 00:00:00,NaN
NumWebVisitsMonth,43170.0,16.59129,1.0,9.0,17.0,25.0,32.0,9.241769